package com.mohammedmustafa.smartcompany;

import android.content.*;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

public class DatabaseHelper extends SQLiteOpenHelper {
    private static final String DB="smart_company.db"; private static final int VER=4;
    public DatabaseHelper(Context c){super(c,DB,null,VER);}
    @Override public void onCreate(SQLiteDatabase d){
        d.execSQL("CREATE TABLE companies(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,currency TEXT DEFAULT 'SDG')");
        d.execSQL("CREATE TABLE accounts(id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT,name TEXT,type TEXT,parent_id INTEGER,active INTEGER DEFAULT 1)");
        d.execSQL("CREATE TABLE products(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,unit TEXT DEFAULT 'وحدة',qty REAL DEFAULT 0,cost REAL DEFAULT 0,price REAL DEFAULT 0)");
        d.execSQL("CREATE TABLE stock_movements(id INTEGER PRIMARY KEY AUTOINCREMENT,product_id INTEGER,type TEXT,qty REAL,unit_cost REAL DEFAULT 0,ref_type TEXT,ref_id INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP)");
        d.execSQL("CREATE TABLE customers(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,phone TEXT,balance REAL DEFAULT 0)");
        d.execSQL("CREATE TABLE suppliers(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,phone TEXT,balance REAL DEFAULT 0)");
        d.execSQL("CREATE TABLE sales(id INTEGER PRIMARY KEY AUTOINCREMENT,customer_id INTEGER,warehouse TEXT DEFAULT 'الرئيسي',total REAL,paid REAL DEFAULT 0,cost_total REAL DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP)");
        d.execSQL("CREATE TABLE sale_items(id INTEGER PRIMARY KEY AUTOINCREMENT,sale_id INTEGER,product_id INTEGER,qty REAL,price REAL,cost REAL)");
        d.execSQL("CREATE TABLE purchases(id INTEGER PRIMARY KEY AUTOINCREMENT,supplier_id INTEGER,warehouse TEXT DEFAULT 'الرئيسي',total REAL,paid REAL DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP)");
        d.execSQL("CREATE TABLE purchase_items(id INTEGER PRIMARY KEY AUTOINCREMENT,purchase_id INTEGER,product_id INTEGER,qty REAL,price REAL)");
        d.execSQL("CREATE TABLE employees(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,job_title TEXT,department TEXT,salary REAL DEFAULT 0,allowances REAL DEFAULT 0,bonus REAL DEFAULT 0,deduction REAL DEFAULT 0,advance_balance REAL DEFAULT 0,active INTEGER DEFAULT 1)");
        d.execSQL("CREATE TABLE advances(id INTEGER PRIMARY KEY AUTOINCREMENT,employee_id INTEGER,amount REAL,installment REAL,start_month TEXT,remaining REAL,created_at TEXT DEFAULT CURRENT_TIMESTAMP)");
        d.execSQL("CREATE TABLE payroll(id INTEGER PRIMARY KEY AUTOINCREMENT,employee_id INTEGER,month TEXT,basic REAL,allowances REAL,bonus REAL,deductions REAL,advance_deduction REAL,net REAL,paid INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP)");
        d.execSQL("CREATE TABLE cash_transactions(id INTEGER PRIMARY KEY AUTOINCREMENT,type TEXT,amount REAL,description TEXT,ref_type TEXT,ref_id INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP)");
        d.execSQL("CREATE TABLE journal(id INTEGER PRIMARY KEY AUTOINCREMENT,description TEXT,ref_type TEXT,ref_id INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP)");
        d.execSQL("CREATE TABLE journal_lines(id INTEGER PRIMARY KEY AUTOINCREMENT,journal_id INTEGER,account TEXT,debit REAL DEFAULT 0,credit REAL DEFAULT 0)");
        d.execSQL("CREATE TABLE audit_log(id INTEGER PRIMARY KEY AUTOINCREMENT,action TEXT,entity TEXT,entity_id INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP)");
        d.execSQL("INSERT INTO companies(name,currency) VALUES('شركة محمد مصطفى الذكية','SDG')");
        String[][] ac={{"1000","الأصول","ASSET"},{"1010","الصندوق","ASSET"},{"1020","البنوك","ASSET"},{"1030","العملاء","ASSET"},{"1040","المخزون","ASSET"},{"2000","الخصوم","LIABILITY"},{"2010","الموردون","LIABILITY"},{"2020","رواتب مستحقة","LIABILITY"},{"3000","حقوق الملكية","EQUITY"},{"4000","المبيعات","REVENUE"},{"5000","تكلفة المبيعات","EXPENSE"},{"5100","المصروفات","EXPENSE"},{"5200","الرواتب","EXPENSE"}};
        for(String[] a:ac){ContentValues v=new ContentValues();v.put("code",a[0]);v.put("name",a[1]);v.put("type",a[2]);d.insert("accounts",null,v);}
    }
    @Override public void onUpgrade(SQLiteDatabase d,int oldV,int newV){ if(oldV<3){d.execSQL("CREATE TABLE IF NOT EXISTS accounts(id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT,name TEXT,type TEXT,parent_id INTEGER,active INTEGER DEFAULT 1)");d.execSQL("CREATE TABLE IF NOT EXISTS advances(id INTEGER PRIMARY KEY AUTOINCREMENT,employee_id INTEGER,amount REAL,installment REAL,start_month TEXT,remaining REAL,created_at TEXT DEFAULT CURRENT_TIMESTAMP)");d.execSQL("CREATE TABLE IF NOT EXISTS payroll(id INTEGER PRIMARY KEY AUTOINCREMENT,employee_id INTEGER,month TEXT,basic REAL,allowances REAL,bonus REAL,deductions REAL,advance_deduction REAL,net REAL,paid INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP)");d.execSQL("CREATE TABLE IF NOT EXISTS cash_transactions(id INTEGER PRIMARY KEY AUTOINCREMENT,type TEXT,amount REAL,description TEXT,ref_type TEXT,ref_id INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP)");} if(oldV<4){d.execSQL("CREATE TABLE IF NOT EXISTS accounts(id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT,name TEXT,type TEXT,parent_id INTEGER,active INTEGER DEFAULT 1)");}}
    private void audit(SQLiteDatabase d,String a,String e,long id){ContentValues v=new ContentValues();v.put("action",a);v.put("entity",e);v.put("entity_id",id);d.insert("audit_log",null,v);}
    private long journal(SQLiteDatabase d,String desc,String type,long ref,double[][] lines,String[] names){ContentValues j=new ContentValues();j.put("description",desc);j.put("ref_type",type);j.put("ref_id",ref);long id=d.insert("journal",null,j);for(int i=0;i<names.length;i++){ContentValues l=new ContentValues();l.put("journal_id",id);l.put("account",names[i]);l.put("debit",lines[i][0]);l.put("credit",lines[i][1]);d.insert("journal_lines",null,l);}return id;}
    public long addProduct(String n,String unit,double q,double cost,double price){SQLiteDatabase d=getWritableDatabase();ContentValues v=new ContentValues();v.put("name",n);v.put("unit",unit);v.put("qty",q);v.put("cost",cost);v.put("price",price);long id=d.insert("products",null,v);if(id>0){ContentValues m=new ContentValues();m.put("product_id",id);m.put("type","OPENING");m.put("qty",q);m.put("unit_cost",cost);m.put("ref_type","OPENING");m.put("ref_id",id);d.insert("stock_movements",null,m);audit(d,"إضافة","صنف",id);}return id;}
    public boolean moveStock(long pid,double q,boolean in){SQLiteDatabase d=getWritableDatabase();d.beginTransaction();try{Cursor c=d.rawQuery("SELECT qty,cost FROM products WHERE id=?",new String[]{""+pid});if(!c.moveToFirst()){c.close();return false;}double old=c.getDouble(0),cost=c.getDouble(1);c.close();if(q<=0||(!in&&old<q))return false;ContentValues p=new ContentValues();p.put("qty",in?old+q:old-q);d.update("products",p,"id=?",new String[]{""+pid});ContentValues m=new ContentValues();m.put("product_id",pid);m.put("type",in?"IN":"OUT");m.put("qty",q);m.put("unit_cost",cost);m.put("ref_type","MANUAL");d.insert("stock_movements",null,m);audit(d,in?"إضافة مخزون":"صرف مخزون","صنف",pid);d.setTransactionSuccessful();return true;}finally{d.endTransaction();}}
    public long addCustomer(String n,String p){ContentValues v=new ContentValues();v.put("name",n);v.put("phone",p);return getWritableDatabase().insert("customers",null,v);}
    public long addSupplier(String n,String p){ContentValues v=new ContentValues();v.put("name",n);v.put("phone",p);return getWritableDatabase().insert("suppliers",null,v);}
    public long addEmployee(String n,String j,String dept,double s,double a,double b,double dd){ContentValues v=new ContentValues();v.put("name",n);v.put("job_title",j);v.put("department",dept);v.put("salary",s);v.put("allowances",a);v.put("bonus",b);v.put("deduction",dd);long id=getWritableDatabase().insert("employees",null,v);audit(getWritableDatabase(),"إضافة","موظف",id);return id;}
    public long addAdvance(long emp,double amount,double installment,String month){ContentValues v=new ContentValues();v.put("employee_id",emp);v.put("amount",amount);v.put("installment",installment);v.put("start_month",month);v.put("remaining",amount);long id=getWritableDatabase().insert("advances",null,v);getWritableDatabase().execSQL("UPDATE employees SET advance_balance=advance_balance+? WHERE id=?",new Object[]{amount,emp});return id;}
    public long addSale(long cid,long pid,double q,double price,double paid){SQLiteDatabase d=getWritableDatabase();d.beginTransaction();try{Cursor c=d.rawQuery("SELECT qty,cost FROM products WHERE id=?",new String[]{""+pid});if(!c.moveToFirst()){c.close();return -1;}double stock=c.getDouble(0),cost=c.getDouble(1);c.close();if(q<=0||stock<q)return -2;double total=q*price,ct=q*cost,recv=total-paid;ContentValues s=new ContentValues();s.put("customer_id",cid);s.put("total",total);s.put("paid",paid);s.put("cost_total",ct);long id=d.insert("sales",null,s);ContentValues it=new ContentValues();it.put("sale_id",id);it.put("product_id",pid);it.put("qty",q);it.put("price",price);it.put("cost",cost);d.insert("sale_items",null,it);ContentValues up=new ContentValues();up.put("qty",stock-q);d.update("products",up,"id=?",new String[]{""+pid});ContentValues mv=new ContentValues();mv.put("product_id",pid);mv.put("type","OUT");mv.put("qty",q);mv.put("unit_cost",cost);mv.put("ref_type","SALE");mv.put("ref_id",id);d.insert("stock_movements",null,mv);if(cid>0&&recv>0)d.execSQL("UPDATE customers SET balance=balance+? WHERE id=?",new Object[]{recv,cid});if(paid>0){ContentValues cv=new ContentValues();cv.put("type","IN");cv.put("amount",paid);cv.put("description","تحصيل بيع #"+id);cv.put("ref_type","SALE");cv.put("ref_id",id);d.insert("cash_transactions",null,cv);}if(recv>0)journal(d,"بيع آجل/جزئي","SALE",id,new double[][]{{paid,0},{recv,0},{0,total},{ct,0},{0,ct}},new String[]{"الصندوق","العملاء","المبيعات","تكلفة المبيعات","المخزون"});else journal(d,"بيع نقدي","SALE",id,new double[][]{{paid,0},{0,total},{ct,0},{0,ct}},new String[]{"الصندوق","المبيعات","تكلفة المبيعات","المخزون"});audit(d,"إضافة","فاتورة بيع",id);d.setTransactionSuccessful();return id;}finally{d.endTransaction();}}
    public long addPurchase(long sid,long pid,double q,double price,double paid){SQLiteDatabase d=getWritableDatabase();d.beginTransaction();try{Cursor c=d.rawQuery("SELECT qty,cost FROM products WHERE id=?",new String[]{""+pid});if(!c.moveToFirst()){c.close();return -1;}double oq=c.getDouble(0),oc=c.getDouble(1);c.close();if(q<=0||price<0)return -2;double total=q*price,nc=(oq+q)==0?price:((oq*oc)+(q*price))/(oq+q),payable=total-paid;ContentValues s=new ContentValues();s.put("supplier_id",sid);s.put("total",total);s.put("paid",paid);long id=d.insert("purchases",null,s);ContentValues it=new ContentValues();it.put("purchase_id",id);it.put("product_id",pid);it.put("qty",q);it.put("price",price);d.insert("purchase_items",null,it);ContentValues up=new ContentValues();up.put("qty",oq+q);up.put("cost",nc);d.update("products",up,"id=?",new String[]{""+pid});ContentValues mv=new ContentValues();mv.put("product_id",pid);mv.put("type","IN");mv.put("qty",q);mv.put("unit_cost",price);mv.put("ref_type","PURCHASE");mv.put("ref_id",id);d.insert("stock_movements",null,mv);if(sid>0&&payable>0)d.execSQL("UPDATE suppliers SET balance=balance+? WHERE id=?",new Object[]{payable,sid});if(paid>0){ContentValues cv=new ContentValues();cv.put("type","OUT");cv.put("amount",paid);cv.put("description","دفع شراء #"+id);cv.put("ref_type","PURCHASE");cv.put("ref_id",id);d.insert("cash_transactions",null,cv);}journal(d,"شراء","PURCHASE",id,new double[][]{{total,0},{0,paid},{0,payable}},new String[]{"المخزون","الصندوق","الموردون"});audit(d,"إضافة","فاتورة شراء",id);d.setTransactionSuccessful();return id;}finally{d.endTransaction();}}
    public long addCash(String type,double amount,String desc){if(amount<=0)return -1;SQLiteDatabase d=getWritableDatabase();ContentValues v=new ContentValues();v.put("type",type);v.put("amount",amount);v.put("description",desc);long id=d.insert("cash_transactions",null,v);journal(d,type.equals("IN")?"سند قبض":"سند صرف",type,id,type.equals("IN")?new double[][]{{amount,0},{0,amount}}:new double[][]{{amount,0},{0,amount}},type.equals("IN")?new String[]{"الصندوق","إيراد متنوع"}:new String[]{"مصروفات","الصندوق"});return id;}
    public long postPayroll(long emp,String month){SQLiteDatabase d=getWritableDatabase();Cursor c=d.rawQuery("SELECT salary,allowances,bonus,deduction,advance_balance FROM employees WHERE id=?",new String[]{""+emp});if(!c.moveToFirst()){c.close();return -1;}double b=c.getDouble(0),a=c.getDouble(1),bo=c.getDouble(2),dd=c.getDouble(3),adv=Math.min(c.getDouble(4),b+a+bo-dd),net=b+a+bo-dd-adv;c.close();ContentValues v=new ContentValues();v.put("employee_id",emp);v.put("month",month);v.put("basic",b);v.put("allowances",a);v.put("bonus",bo);v.put("deductions",dd);v.put("advance_deduction",adv);v.put("net",net);long id=d.insert("payroll",null,v);d.execSQL("UPDATE employees SET advance_balance=advance_balance-? WHERE id=?",new Object[]{adv,emp});journal(d,"راتب "+month,"PAYROLL",id,new double[][]{{net,0},{0,net}},new String[]{"الرواتب","الصندوق"});return id;}
    public double inventoryValue(){return scalar("SELECT COALESCE(SUM(qty*cost),0) FROM products");} public double salesTotal(){return scalar("SELECT COALESCE(SUM(total),0) FROM sales");} public double purchasesTotal(){return scalar("SELECT COALESCE(SUM(total),0) FROM purchases");} public double payroll(){return scalar("SELECT COALESCE(SUM(salary+allowances+bonus-deduction),0) FROM employees WHERE active=1");} public double cashBalance(){return scalar("SELECT COALESCE(SUM(CASE WHEN type='IN' THEN amount ELSE -amount END),0) FROM cash_transactions");} public double cogs(){return scalar("SELECT COALESCE(SUM(cost_total),0) FROM sales");} public double netResult(){return salesTotal()-cogs()-scalar("SELECT COALESCE(SUM(net),0) FROM payroll")-scalar("SELECT COALESCE(SUM(amount),0) FROM cash_transactions WHERE type='OUT' AND description NOT LIKE 'دفع شراء%'");}
    private double scalar(String q){Cursor c=getReadableDatabase().rawQuery(q,null);double x=c.moveToFirst()?c.getDouble(0):0;c.close();return x;}
}