package com.mohammedmustafa.smartcompany;
import android.app.*;import android.os.*;import android.graphics.Color;import android.text.InputType;import android.view.*;import android.widget.*;import android.database.Cursor;import android.content.SharedPreferences;import android.content.Context;import android.content.Intent;import android.net.Uri;import android.print.PrintAttributes;import android.print.PrintDocumentAdapter;import android.print.PrintManager;import android.webkit.WebView;import android.webkit.WebViewClient;import java.security.MessageDigest;import java.nio.charset.StandardCharsets;
public class MainActivity{
 DatabaseHelper db;LinearLayout content;SharedPreferences prefs;boolean unlocked=false;boolean loginDialogShown=false;
 @Override public void onCreate(Bundle b){super.onCreate(b);db=new DatabaseHelper(this);prefs=getSharedPreferences("security",MODE_PRIVATE);if(!prefs.contains("password_hash")){showSetPassword();}else{showLock();}}
 @Override protected void onPause(){super.onPause();if(unlocked)unlocked=false;}
 @Override protected void onResume(){super.onResume();if(prefs!=null&&prefs.contains("password_hash")&&!unlocked&&!loginDialogShown&&content!=null)showLock();}
 String hash(String x){try{MessageDigest d=MessageDigest.getInstance("SHA-256");byte[] b=d.digest(x.getBytes(StandardCharsets.UTF_8));StringBuilder s=new StringBuilder();for(byte q:b)s.append(String.format("%02x",q));return s.toString();}catch(Exception e){return "";}}
 void showSetPassword(){loginDialogShown=true;final EditText a=f("أنشئ كلمة المرور",false);final EditText b=f("أعد إدخال كلمة المرور",false);a.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);b.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);new AlertDialog.Builder(this).setTitle("تأمين التطبيق").setMessage("أنشئ كلمة مرور لقفل التطبيق. احفظها في مكان آمن؛ لا يمكن فتح البيانات بدونها.").setView(box(a,b)).setCancelable(false).setPositiveButton("حفظ",(d,w)->{if(a.length()<4||!a.getText().toString().equals(b.getText().toString())){toast("كلمة المرور يجب أن تتطابق وأن تكون 4 أحرف/أرقام على الأقل");loginDialogShown=false;showSetPassword();return;}prefs.edit().putString("password_hash",hash(a.getText().toString())).apply();unlocked=true;loginDialogShown=false;build();}).show();}
 void showLock(){loginDialogShown=true;final EditText a=f("كلمة المرور",false);a.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);new AlertDialog.Builder(this).setTitle("التطبيق مقفل").setMessage("أدخل كلمة المرور للمتابعة").setView(a).setCancelable(false).setPositiveButton("فتح",(d,w)->{if(hash(a.getText().toString()).equals(prefs.getString("password_hash",""))){unlocked=true;loginDialogShown=false;build();}else{toast("كلمة المرور غير صحيحة");loginDialogShown=false;showLock();}}).setNegativeButton("خروج",(d,w)->finish()).show();}
 void changePassword(){final EditText a=f("كلمة المرور الحالية",false),b=f("كلمة المرور الجديدة",false),c=f("تأكيد الجديدة",false);a.setInputType(129);b.setInputType(129);c.setInputType(129);new AlertDialog.Builder(this).setTitle("تغيير كلمة المرور").setView(box(a,b,c)).setPositiveButton("حفظ",(d,w)->{if(!hash(a.getText().toString()).equals(prefs.getString("password_hash",""))){toast("كلمة المرور الحالية غير صحيحة");return;}if(b.length()<4||!b.getText().toString().equals(c.getText().toString())){toast("كلمة المرور الجديدة غير متطابقة أو قصيرة");return;}prefs.edit().putString("password_hash",hash(b.getText().toString())).apply();toast("تم تغيير كلمة المرور");}).setNegativeButton("إلغاء",null).show();}
 TextView tv(String s,int z){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setPadding(16,14,16,14);return t;} Button btn(String s,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setOnClickListener(l);return b;} EditText f(String h,boolean n){EditText e=new EditText(this);e.setHint(h);e.setPadding(12,8,12,8);if(n)e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);return e;} LinearLayout box(EditText...e){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);for(EditText a:e)x.addView(a);return x;} double n(EditText e){return Double.parseDouble(e.getText().toString());}String m(double x){return String.format(java.util.Locale.US,"%.2f جنيه",x);}void clear(String s){content.removeAllViews();content.addView(tv(s,22));}
 void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);TextView h=tv("شركة محمد مصطفى الذكية\nالمحاسبة وإدارة الشركات",23);h.setGravity(17);h.setTextColor(Color.rgb(11,31,58));root.addView(h);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);ScrollView sv=new ScrollView(this);sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));LinearLayout nav=new LinearLayout(this);nav.addView(btn("الرئيسية",v->home()),new LinearLayout.LayoutParams(0,-2,1));nav.addView(btn("بيع",v->sales()),new LinearLayout.LayoutParams(0,-2,1));nav.addView(btn("شراء",v->purchases()),new LinearLayout.LayoutParams(0,-2,1));nav.addView(btn("تقارير",v->reports()),new LinearLayout.LayoutParams(0,-2,1));root.addView(nav);setContentView(root);home();}
 void home(){clear("لوحة التحكم");content.addView(tv("قيمة المخزون: "+m(db.inventoryValue())+"\nالصندوق: "+m(db.cashBalance())+"\nالمبيعات: "+m(db.salesTotal())+"\nالمشتريات: "+m(db.purchasesTotal())+"\nالرواتب الحالية: "+m(db.payroll())+"\nصافي النتيجة التقديرية: "+m(db.netResult()),17));content.addView(tv("أدخل العملية مرة واحدة؛ النظام يربط المخزون والعملاء والموردين والصندوق والقيود تلقائيًا.",15));content.addView(btn("إضافة صنف",v->productDialog()));content.addView(btn("إضافة عميل",v->customerDialog()));content.addView(btn("إضافة مورد",v->supplierDialog()));content.addView(btn("إضافة موظف",v->employeeDialog()));content.addView(btn("سند قبض / صرف",v->cashDialog()));content.addView(btn("سلفة موظف",v->advanceDialog()));content.addView(btn("ترحيل راتب",v->payrollDialog()));content.addView(btn("👤 اسم المحاسب والتوقيع على المطبوعات",v->accountantDialog()));content.addView(btn("✉️ مراسلة عبر البريد الإلكتروني",v->emailDialog()));content.addView(btn("🔐 تغيير كلمة مرور التطبيق",v->changePassword()));}
 void productDialog(){EditText a=f("اسم الصنف",false),b=f("الكمية",true),c=f("التكلفة",true),d=f("سعر البيع",true);new AlertDialog.Builder(this).setTitle("إضافة صنف").setView(box(a,b,c,d)).setPositiveButton("حفظ",(x,w)->{try{db.addProduct(a.getText().toString(),"وحدة",n(b),n(c),n(d));home();}catch(Exception e){toast("بيانات غير صحيحة");}}).setNegativeButton("إلغاء",null).show();}
 void customerDialog(){EditText a=f("اسم العميل",false),b=f("الهاتف",false);new AlertDialog.Builder(this).setTitle("إضافة عميل").setView(box(a,b)).setPositiveButton("حفظ",(x,w)->{db.addCustomer(a.getText().toString(),b.getText().toString());toast("تم حفظ العميل");}).setNegativeButton("إلغاء",null).show();}
 void supplierDialog(){EditText a=f("اسم المورد",false),b=f("الهاتف",false);new AlertDialog.Builder(this).setTitle("إضافة مورد").setView(box(a,b)).setPositiveButton("حفظ",(x,w)->{db.addSupplier(a.getText().toString(),b.getText().toString());toast("تم حفظ المورد");}).setNegativeButton("إلغاء",null).show();}
 void employeeDialog(){EditText a=f("اسم الموظف",false),b=f("المسمى الوظيفي",false),c=f("الراتب الأساسي",true),d=f("البدلات",true),e=f("الحوافز",true),g=f("الخصومات",true);new AlertDialog.Builder(this).setTitle("إضافة موظف").setView(box(a,b,c,d,e,g)).setPositiveButton("حفظ",(x,w)->{try{db.addEmployee(a.getText().toString(),b.getText().toString(),"عام",n(c),n(d),n(e),n(g));toast("تم حفظ الموظف");}catch(Exception z){toast("بيانات غير صحيحة");}}).setNegativeButton("إلغاء",null).show();}
 void sales(){clear("المبيعات");content.addView(btn("تسجيل فاتورة بيع",v->saleDialog()));Cursor c=db.getReadableDatabase().rawQuery("SELECT id,total,paid,created_at FROM sales ORDER BY id DESC",null);while(c.moveToNext()){long id=c.getLong(0);content.addView(tv("فاتورة #"+id+" | "+m(c.getDouble(1))+" | مدفوع "+m(c.getDouble(2))+"\n"+c.getString(3),15));content.addView(btn("🖨 طباعة الفاتورة #"+id,v->printInvoice("SALE",id)));}c.close();}
 void saleDialog(){EditText a=f("رقم العميل (0 نقدي)",true),b=f("رقم الصنف",true),c=f("الكمية",true),d=f("سعر الوحدة",true),e=f("المدفوع",true);new AlertDialog.Builder(this).setTitle("فاتورة بيع").setView(box(a,b,c,d,e)).setPositiveButton("تنفيذ",(x,w)->{try{long id=db.addSale((long)n(a),(long)n(b),n(c),n(d),n(e));toast(id>0?"تم البيع وتحديث المخزون والقيود":"تعذر تنفيذ البيع");sales();}catch(Exception z){toast("بيانات غير صحيحة");}}).setNegativeButton("إلغاء",null).show();}
 void purchases(){clear("المشتريات");content.addView(btn("تسجيل فاتورة شراء",v->purchaseDialog()));Cursor c=db.getReadableDatabase().rawQuery("SELECT id,total,paid,created_at FROM purchases ORDER BY id DESC",null);while(c.moveToNext()){long id=c.getLong(0);content.addView(tv("فاتورة #"+id+" | "+m(c.getDouble(1))+" | مدفوع "+m(c.getDouble(2))+"\n"+c.getString(3),15));content.addView(btn("🖨 طباعة الفاتورة #"+id,v->printInvoice("PURCHASE",id)));}c.close();}
 void purchaseDialog(){EditText a=f("رقم المورد (0 نقدي)",true),b=f("رقم الصنف",true),c=f("الكمية",true),d=f("سعر الشراء",true),e=f("المدفوع",true);new AlertDialog.Builder(this).setTitle("فاتورة شراء").setView(box(a,b,c,d,e)).setPositiveButton("تنفيذ",(x,w)->{try{long id=db.addPurchase((long)n(a),(long)n(b),n(c),n(d),n(e));toast(id>0?"تم الشراء وتحديث المخزون والقيود":"تعذر تنفيذ الشراء");purchases();}catch(Exception z){toast("بيانات غير صحيحة");}}).setNegativeButton("إلغاء",null).show();}
 void cashDialog(){EditText a=f("المبلغ",true),b=f("البيان",false);new AlertDialog.Builder(this).setTitle("سند نقدية").setView(box(a,b)).setPositiveButton("قبض",(x,w)->{try{db.addCash("IN",n(a),b.getText().toString());home();}catch(Exception e){toast("بيانات غير صحيحة");}}).setNeutralButton("صرف",(x,w)->{try{db.addCash("OUT",n(a),b.getText().toString());home();}catch(Exception e){toast("بيانات غير صحيحة");}}).setNegativeButton("إلغاء",null).show();}
 void advanceDialog(){EditText a=f("رقم الموظف",true),b=f("قيمة السلفة",true),c=f("قسط شهري",true),d=f("شهر البداية YYYY-MM",false);new AlertDialog.Builder(this).setTitle("سلفة موظف").setView(box(a,b,c,d)).setPositiveButton("حفظ",(x,w)->{try{db.addAdvance((long)n(a),n(b),n(c),d.getText().toString());toast("تم تسجيل السلفة");}catch(Exception e){toast("بيانات غير صحيحة");}}).setNegativeButton("إلغاء",null).show();}
 void payrollDialog(){EditText a=f("رقم الموظف",true),b=f("الشهر YYYY-MM",false);new AlertDialog.Builder(this).setTitle("ترحيل راتب").setView(box(a,b)).setPositiveButton("ترحيل",(x,w)->{try{long id=db.postPayroll((long)n(a),b.getText().toString());toast(id>0?"تم ترحيل الراتب وخصم قسط السلفة":"تعذر الترحيل");}catch(Exception e){toast("بيانات غير صحيحة");}}).setNegativeButton("إلغاء",null).show();}
 void reports(){clear("التقارير المالية");content.addView(tv("ملخص مالي\n\nالمخزون: "+m(db.inventoryValue())+"\nالصندوق: "+m(db.cashBalance())+"\nالمبيعات: "+m(db.salesTotal())+"\nتكلفة المبيعات: "+m(db.cogs())+"\nالمشتريات: "+m(db.purchasesTotal())+"\nالرواتب الحالية: "+m(db.payroll())+"\nصافي النتيجة التقديرية: "+m(db.netResult()),17));content.addView(btn("🖨 طباعة الملخص المالي",v->printFinancialReport()));content.addView(btn("دليل الحسابات",v->accounts()));content.addView(btn("القيود اليومية",v->journal()));content.addView(btn("المخزون",v->inventory()));content.addView(btn("الموظفون والسلف",v->employees()));}
 void accounts(){clear("دليل الحسابات");Cursor c=db.getReadableDatabase().rawQuery("SELECT code,name,type FROM accounts ORDER BY code",null);while(c.moveToNext())content.addView(tv(c.getString(0)+" | "+c.getString(1)+" | "+c.getString(2),15));c.close();}
 void journal(){clear("القيود اليومية");Cursor c=db.getReadableDatabase().rawQuery("SELECT j.id,j.description,COALESCE(SUM(l.debit),0),COALESCE(SUM(l.credit),0),j.created_at FROM journal j LEFT JOIN journal_lines l ON l.journal_id=j.id GROUP BY j.id ORDER BY j.id DESC",null);while(c.moveToNext())content.addView(tv("قيد #"+c.getLong(0)+" | "+c.getString(1)+"\nمدين "+m(c.getDouble(2))+" = دائن "+m(c.getDouble(3))+"\n"+c.getString(4),15));c.close();}
 void inventory(){clear("المخزون");Cursor c=db.getReadableDatabase().rawQuery("SELECT id,name,qty,cost,price FROM products ORDER BY id DESC",null);while(c.moveToNext())content.addView(tv("#"+c.getLong(0)+" | "+c.getString(1)+"\nالكمية "+c.getDouble(2)+" | التكلفة "+m(c.getDouble(3))+" | البيع "+m(c.getDouble(4)),15));c.close();}
 void employees(){clear("الموظفون والسلف");Cursor c=db.getReadableDatabase().rawQuery("SELECT id,name,job_title,salary,allowances,bonus,deduction,advance_balance FROM employees WHERE active=1 ORDER BY id DESC",null);while(c.moveToNext())content.addView(tv("#"+c.getLong(0)+" | "+c.getString(1)+" | "+c.getString(2)+"\nالصافي قبل قسط السلفة: "+m(c.getDouble(3)+c.getDouble(4)+c.getDouble(5)-c.getDouble(6))+" | رصيد السلفة: "+m(c.getDouble(7)),15));c.close();}
 void emailDialog(){final EditText to=f("البريد الإلكتروني للمستلم",false),sub=f("موضوع الرسالة",false),body=f("نص الرسالة",false);body.setMinLines(5);body.setGravity(48);new AlertDialog.Builder(this).setTitle("مراسلة بالبريد الإلكتروني").setView(box(to,sub,body)).setPositiveButton("إرسال",(d,w)->{String addr=to.getText().toString().trim();String subject=sub.getText().toString();String text=body.getText().toString();if(addr.isEmpty()){toast("أدخل البريد الإلكتروني للمستلم");return;}Intent i=new Intent(Intent.ACTION_SENDTO);i.setData(Uri.parse("mailto:"+Uri.encode(addr)));i.putExtra(Intent.EXTRA_SUBJECT,subject);i.putExtra(Intent.EXTRA_TEXT,text);try{startActivity(Intent.createChooser(i,"اختر تطبيق البريد الإلكتروني"));}catch(Exception e){toast("لا يوجد تطبيق بريد إلكتروني مثبت على الهاتف");}}).setNegativeButton("إلغاء",null).show();}
 void accountantDialog(){final EditText a=f("اسم المحاسب كما يظهر أسفل الفاتورة",false);a.setText(prefs.getString("accountant_name",""));new AlertDialog.Builder(this).setTitle("بيانات المحاسب").setMessage("سيظهر الاسم تلقائيًا في أسفل كل فاتورة وتقرير يتم إرساله للطابعة.").setView(a).setPositiveButton("حفظ",(d,w)->{String name=a.getText().toString().trim();prefs.edit().putString("accountant_name",name).apply();toast(name.isEmpty()?"تم حذف اسم المحاسب من المطبوعات":"تم حفظ اسم المحاسب للمطبوعات");}).setNegativeButton("إلغاء",null).show();}
String accountant(){String x=prefs.getString("accountant_name","").trim();return x.isEmpty()?"غير محدد":x;}
String esc(String x){if(x==null)return "";return x.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace(""","&quot;");}
void printHtml(String title,String html){final WebView w=new WebView(this);w.getSettings().setJavaScriptEnabled(false);w.setWebViewClient(new WebViewClient(){@Override public void onPageFinished(WebView v,String u){PrintManager pm=(PrintManager)getSystemService(Context.PRINT_SERVICE);PrintDocumentAdapter ad=v.createPrintDocumentAdapter(title);pm.print(title,ad,new PrintAttributes.Builder().setMediaSize(PrintAttributes.MediaSize.ISO_A4).setMinMargins(PrintAttributes.Margins.NO_MARGINS).build());}});w.loadDataWithBaseURL(null,html,"text/html","UTF-8",null);}
void printInvoice(String type,long id){Cursor c=null;try{String table=type.equals("SALE")?"sales":"purchases";String party=type.equals("SALE")?"customer_id":"supplier_id";c=db.getReadableDatabase().rawQuery("SELECT id,total,paid,created_at,"+party+" FROM "+table+" WHERE id=?",new String[]{""+id});if(!c.moveToFirst()){toast("الفاتورة غير موجودة");return;}double total=c.getDouble(1),paid=c.getDouble(2);String date=c.getString(3);String kind=type.equals("SALE")?"فاتورة بيع":"فاتورة شراء";String html="<html dir='rtl'><meta charset='utf-8'><style>body{font-family:sans-serif;padding:28px;direction:rtl}h1{text-align:center;color:#0B1F3A}.box{border:1px solid #999;padding:12px;margin:12px 0}.sign{margin-top:70px;border-top:1px solid #333;padding-top:10px;width:45%}</style><h1>شركة محمد مصطفى الذكية</h1><h2>"+kind+" رقم #"+id+"</h2><div class='box'>التاريخ: "+esc(date)+"<br>رقم الطرف: "+c.getLong(4)+"<br>الإجمالي: "+m(total)+"<br>المدفوع: "+m(paid)+"<br>المتبقي: "+m(total-paid)+"</div><p>تم تسجيل العملية وترحيلها إلى السجلات المحاسبية والمخزون.</p><div class='sign'><b>توقيع المحاسب</b><br>"+esc(accountant())+"</div></html>";printHtml(kind+" #"+id,html);}finally{if(c!=null)c.close();}}
void printFinancialReport(){String html="<html dir='rtl'><meta charset='utf-8'><style>body{font-family:sans-serif;padding:28px;direction:rtl}h1{text-align:center;color:#0B1F3A}table{width:100%;border-collapse:collapse}td,th{border:1px solid #777;padding:9px}</style><h1>شركة محمد مصطفى الذكية</h1><h2>الملخص المالي</h2><table><tr><th>البند</th><th>القيمة</th></tr><tr><td>المخزون</td><td>"+m(db.inventoryValue())+"</td></tr><tr><td>الصندوق</td><td>"+m(db.cashBalance())+"</td></tr><tr><td>المبيعات</td><td>"+m(db.salesTotal())+"</td></tr><tr><td>تكلفة المبيعات</td><td>"+m(db.cogs())+"</td></tr><tr><td>المشتريات</td><td>"+m(db.purchasesTotal())+"</td></tr><tr><td>الرواتب</td><td>"+m(db.payroll())+"</td></tr><tr><td>صافي النتيجة التقديرية</td><td>"+m(db.netResult())+"</td></tr></table><div style='margin-top:80px;border-top:1px solid #333;width:45%;padding-top:10px'><b>توقيع المحاسب</b><br>"+esc(accountant())+"</div></html>";printHtml("الملخص المالي",html);}
void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
}