package com.mohammedmustafa.smartcompany;

import android.app.*;
import android.os.*;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import android.content.*;
import android.net.Uri;
import java.security.MessageDigest;
import java.nio.charset.StandardCharsets;
import android.database.Cursor;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import android.print.PrintManager;

public class MainActivity extends Activity {
    DatabaseHelper db; SharedPreferences prefs; LicenseManager license;
    LinearLayout content; boolean unlocked=false, dialogOpen=false;
    final int NAVY=Color.rgb(11,31,58), GOLD=Color.rgb(212,175,55), BG=Color.rgb(248,249,250);

    @Override public void onCreate(Bundle b){super.onCreate(b); db=new DatabaseHelper(this); prefs=getSharedPreferences("security",MODE_PRIVATE); license=new LicenseManager(this); if(!license.isTrialValid()){showActivation();return;} if(!prefs.contains("password_hash")) setDefaultPassword(); else showLock();}
    @Override protected void onPause(){super.onPause(); if(unlocked) unlocked=false;}
    @Override protected void onResume(){super.onResume(); if(license!=null&&!license.isTrialValid()&&!dialogOpen){showActivation();} else if(prefs!=null&&prefs.contains("password_hash")&&!unlocked&&!dialogOpen&&content!=null)showLock();}

    String hash(String x){try{MessageDigest d=MessageDigest.getInstance("SHA-256");byte[] b=d.digest(x.getBytes(StandardCharsets.UTF_8));StringBuilder s=new StringBuilder();for(byte q:b)s.append(String.format("%02x",q));return s.toString();}catch(Exception e){return "";}}
    void setDefaultPassword(){prefs.edit().putString("password_hash",hash("1234")).apply(); unlocked=true; build();}
    EditText field(String hint,boolean number){EditText e=new EditText(this);e.setHint(hint);e.setPadding(14,8,14,8);if(number)e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);return e;}
    LinearLayout box(EditText... es){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(18,4,18,4);for(EditText e:es)x.addView(e);return x;}
    TextView text(String s,float size){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(NAVY);t.setPadding(16,12,16,12);return t;}
    Button action(String s,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setTextSize(14);b.setAllCaps(false);b.setOnClickListener(l);return b;}
    double num(EditText e){return Double.parseDouble(e.getText().toString());}
    String money(double x){return String.format(java.util.Locale.US,"%,.2f جنيه",x);}
    void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}

    void showLock(){if(dialogOpen)return;dialogOpen=true;EditText p=field("كلمة المرور",false);p.setInputType(129);new AlertDialog.Builder(this).setTitle("🔐 التطبيق مقفل").setMessage("كلمة المرور الافتراضية: 1234 ويمكن تغييرها من الإعدادات.").setView(p).setCancelable(false).setPositiveButton("دخول",(d,w)->{dialogOpen=false;if(hash(p.getText().toString()).equals(prefs.getString("password_hash",""))){unlocked=true;build();}else{toast("كلمة المرور غير صحيحة");showLock();}}).setNegativeButton("خروج",(d,w)->finish()).show();}
    void showActivation(){if(dialogOpen)return;dialogOpen=true;int days=license.remainingDays();EditText code=field("رمز التفعيل",false);String msg=days>0?"التجربة المجانية: "+days+" يوم متبقٍ.":"انتهت التجربة المجانية لمدة 7 أيام.\nأدخل رمز التفعيل بعد شراء الترخيص.";new AlertDialog.Builder(this).setTitle("⭐ SmartCompany Pro").setMessage(msg+"\nيمكن تحديث الترخيص لاحقًا دون إعادة تثبيت التطبيق.").setView(box(code)).setCancelable(false).setPositiveButton("تفعيل",(d,w)->{dialogOpen=false;if(license.activate(code.getText().toString())){toast("تم تفعيل الترخيص");unlocked=true;build();}else{toast("رمز التفعيل غير صالح");showActivation();}}).setNegativeButton("خروج",(d,w)->finish()).show();}

    void build(){
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);
        LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.VERTICAL);head.setPadding(18,14,18,8);
        TextView title=text("شركة محمد مصطفى الذكية",23);title.setTextColor(NAVY);title.setTypeface(null,1);title.setGravity(Gravity.CENTER);
        TextView sub=text("SmartCompany • إدارة المحاسبة والشركة",14);sub.setGravity(Gravity.CENTER);head.addView(title);head.addView(sub);root.addView(head);
        content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);ScrollView scroll=new ScrollView(this);scroll.addView(content);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        LinearLayout nav=new LinearLayout(this);nav.setPadding(4,2,4,4);nav.addView(action("⌂ الرئيسية",v->home()),new LinearLayout.LayoutParams(0,-2,1));nav.addView(action("↩ رجوع",v->home()),new LinearLayout.LayoutParams(0,-2,1));nav.addView(action("⚙ الإعدادات",v->settings()),new LinearLayout.LayoutParams(0,-2,1));root.addView(nav);setContentView(root);home();
    }

    Button module(String icon,String name,View.OnClickListener l){Button b=action(icon+"\n"+name,l);b.setTextSize(15);b.setTextColor(NAVY);GradientDrawable g=new GradientDrawable();g.setColor(Color.WHITE);g.setCornerRadius(22);g.setStroke(2,GOLD);b.setBackground(g);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,145,1);p.setMargins(7,7,7,7);b.setLayoutParams(p);return b;}
    void home(){content.removeAllViews();TextView trial=text(license.isActivated()?"✓ الترخيص مفعل":"⏱ التجربة المجانية — "+license.remainingDays()+" يوم متبقٍ",14);trial.setGravity(Gravity.CENTER);trial.setTextColor(license.isActivated()?Color.rgb(0,110,70):NAVY);content.addView(trial);
        TextView dash=text("لوحة القيادة\nالمخزون: "+money(db.inventoryValue())+"   |   الصندوق: "+money(db.cashBalance())+"\nالمبيعات: "+money(db.salesTotal())+"   |   المشتريات: "+money(db.purchasesTotal())+"\nالنتيجة التقديرية: "+money(db.netResult()),15);content.addView(dash);
        GridLayout grid=new GridLayout(this);grid.setColumnCount(2);grid.setPadding(5,5,5,12);content.addView(grid);
        grid.addView(module("📊","لوحة القيادة",v->home()));grid.addView(module("🧾","المبيعات والفواتير",v->sales()));
        grid.addView(module("🛒","المشتريات",v->purchases()));grid.addView(module("📦","المخزون والمخازن",v->inventory()));
        grid.addView(module("👥","العملاء",v->customers()));grid.addView(module("🚚","الموردون",v->suppliers()));
        grid.addView(module("👔","الموظفون والرواتب",v->employees()));grid.addView(module("📒","الحسابات والقيود",v->accounts()));
        grid.addView(module("📈","التقارير المالية",v->reports()));grid.addView(module("💵","الصندوق",v->cash()));
        grid.addView(module("🖨️","الطباعة",v->reports()));grid.addView(module("✉️","البريد الإلكتروني",v->emailDialog()));
    }
    void header(String title){content.removeAllViews();LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);TextView t=text(title,22);t.setTypeface(null,1);h.addView(action("← الرئيسية",v->home()),new LinearLayout.LayoutParams(-2,-2));h.addView(t,new LinearLayout.LayoutParams(0,-2,1));content.addView(h);}

    void sales(){header("🧾 المبيعات والفواتير");content.addView(action("＋ فاتورة بيع جديدة",v->saleDialog()));Cursor c=db.getReadableDatabase().rawQuery("SELECT id,total,paid,created_at FROM sales ORDER BY id DESC",null);while(c.moveToNext()){long id=c.getLong(0);content.addView(text("فاتورة #"+id+"  |  الإجمالي "+money(c.getDouble(1))+"  |  المدفوع "+money(c.getDouble(2))+"\n"+c.getString(3),15));content.addView(action("🖨️ طباعة الفاتورة",v->printInvoice("SALE",id)));}c.close();}
    void saleDialog(){EditText a=field("رقم العميل (0 نقدي)",true),b=field("رقم الصنف",true),q=field("الكمية",true),p=field("سعر الوحدة",true),paid=field("المدفوع",true);new AlertDialog.Builder(this).setTitle("فاتورة بيع").setView(box(a,b,q,p,paid)).setPositiveButton("حفظ وترحيل",(d,w)->{try{long id=db.addSale((long)num(a),(long)num(b),num(q),num(p),num(paid));toast(id>0?"✓ تم البيع وتحديث المخزون والقيود":"تعذر تنفيذ البيع");sales();}catch(Exception e){toast("تحقق من البيانات");}}).setNegativeButton("إلغاء",null).show();}

    void purchases(){header("🛒 المشتريات");content.addView(action("＋ فاتورة شراء جديدة",v->purchaseDialog()));Cursor c=db.getReadableDatabase().rawQuery("SELECT id,total,paid,created_at FROM purchases ORDER BY id DESC",null);while(c.moveToNext()){long id=c.getLong(0);content.addView(text("فاتورة #"+id+"  |  الإجمالي "+money(c.getDouble(1))+"  |  المدفوع "+money(c.getDouble(2))+"\n"+c.getString(3),15));content.addView(action("🖨️ طباعة الفاتورة",v->printInvoice("PURCHASE",id)));}c.close();}
    void purchaseDialog(){EditText a=field("رقم المورد (0 نقدي)",true),b=field("رقم الصنف",true),q=field("الكمية",true),p=field("سعر الشراء",true),paid=field("المدفوع",true);new AlertDialog.Builder(this).setTitle("فاتورة شراء").setView(box(a,b,q,p,paid)).setPositiveButton("حفظ وترحيل",(d,w)->{try{long id=db.addPurchase((long)num(a),(long)num(b),num(q),num(p),num(paid));toast(id>0?"✓ تم الشراء وتحديث المخزون والقيود":"تعذر تنفيذ الشراء");purchases();}catch(Exception e){toast("تحقق من البيانات");}}).setNegativeButton("إلغاء",null).show();}

    void inventory(){header("📦 المخزون والمخازن");content.addView(action("＋ إضافة صنف",v->productDialog()));Cursor c=db.getReadableDatabase().rawQuery("SELECT id,name,qty,cost,price FROM products ORDER BY id DESC",null);while(c.moveToNext())content.addView(text("#"+c.getLong(0)+"  "+c.getString(1)+"\nالكمية: "+c.getDouble(2)+"  | التكلفة: "+money(c.getDouble(3))+"  | البيع: "+money(c.getDouble(4)),15));c.close();}
    void productDialog(){EditText n=field("اسم الصنف",false),q=field("الكمية الافتتاحية",true),c=field("التكلفة",true),p=field("سعر البيع",true);new AlertDialog.Builder(this).setTitle("إضافة صنف").setView(box(n,q,c,p)).setPositiveButton("حفظ",(d,w)->{try{db.addProduct(n.getText().toString(),"وحدة",num(q),num(c),num(p));inventory();}catch(Exception e){toast("تحقق من البيانات");}}).setNegativeButton("إلغاء",null).show();}

    void customers(){header("👥 العملاء");content.addView(action("＋ إضافة عميل",v->customerDialog()));Cursor c=db.getReadableDatabase().rawQuery("SELECT id,name,phone,balance FROM customers ORDER BY id DESC",null);while(c.moveToNext())content.addView(text("#"+c.getLong(0)+"  "+c.getString(1)+"\n"+c.getString(2)+"  | الرصيد: "+money(c.getDouble(3)),15));c.close();}
    void customerDialog(){EditText n=field("اسم العميل",false),p=field("الهاتف",false);new AlertDialog.Builder(this).setTitle("عميل جديد").setView(box(n,p)).setPositiveButton("حفظ",(d,w)->{db.addCustomer(n.getText().toString(),p.getText().toString());customers();}).setNegativeButton("إلغاء",null).show();}
    void suppliers(){header("🚚 الموردون");content.addView(action("＋ إضافة مورد",v->supplierDialog()));Cursor c=db.getReadableDatabase().rawQuery("SELECT id,name,phone,balance FROM suppliers ORDER BY id DESC",null);while(c.moveToNext())content.addView(text("#"+c.getLong(0)+"  "+c.getString(1)+"\n"+c.getString(2)+"  | الرصيد: "+money(c.getDouble(3)),15));c.close();}
    void supplierDialog(){EditText n=field("اسم المورد",false),p=field("الهاتف",false);new AlertDialog.Builder(this).setTitle("مورد جديد").setView(box(n,p)).setPositiveButton("حفظ",(d,w)->{db.addSupplier(n.getText().toString(),p.getText().toString());suppliers();}).setNegativeButton("إلغاء",null).show();}

    void employees(){header("👔 الموظفون والرواتب");content.addView(action("＋ إضافة موظف",v->employeeDialog()));content.addView(action("＋ تسجيل سلفة",v->advanceDialog()));content.addView(action("✓ ترحيل راتب",v->payrollDialog()));Cursor c=db.getReadableDatabase().rawQuery("SELECT id,name,job_title,salary,allowances,bonus,deduction,advance_balance FROM employees WHERE active=1 ORDER BY id DESC",null);while(c.moveToNext())content.addView(text("#"+c.getLong(0)+"  "+c.getString(1)+" — "+c.getString(2)+"\nالراتب: "+money(c.getDouble(3)+c.getDouble(4)+c.getDouble(5)-c.getDouble(6))+"  | السلفة المتبقية: "+money(c.getDouble(7)),15));c.close();}
    void employeeDialog(){EditText n=field("اسم الموظف",false),j=field("المسمى الوظيفي",false),s=field("الأساسي",true),a=field("البدلات",true),b=field("الحوافز",true),d=field("الخصومات",true);new AlertDialog.Builder(this).setTitle("موظف جديد").setView(box(n,j,s,a,b,d)).setPositiveButton("حفظ",(x,w)->{try{db.addEmployee(n.getText().toString(),j.getText().toString(),"عام",num(s),num(a),num(b),num(d));employees();}catch(Exception e){toast("تحقق من البيانات");}}).setNegativeButton("إلغاء",null).show();}
    void advanceDialog(){EditText e=field("رقم الموظف",true),a=field("قيمة السلفة",true),i=field("القسط الشهري",true),m=field("شهر البداية YYYY-MM",false);new AlertDialog.Builder(this).setTitle("سلفة موظف").setView(box(e,a,i,m)).setPositiveButton("حفظ",(d,w)->{try{db.addAdvance((long)num(e),num(a),num(i),m.getText().toString());employees();}catch(Exception z){toast("تحقق من البيانات");}}).setNegativeButton("إلغاء",null).show();}
    void payrollDialog(){EditText e=field("رقم الموظف",true),m=field("الشهر YYYY-MM",false);new AlertDialog.Builder(this).setTitle("ترحيل راتب").setView(box(e,m)).setPositiveButton("ترحيل",(d,w)->{try{long id=db.postPayroll((long)num(e),m.getText().toString());toast(id>0?"✓ تم ترحيل الراتب":"تعذر الترحيل");employees();}catch(Exception z){toast("تحقق من البيانات");}}).setNegativeButton("إلغاء",null).show();}

    void accounts(){header("📒 الحسابات والقيود");content.addView(text("دليل الحسابات",19));Cursor c=db.getReadableDatabase().rawQuery("SELECT code,name,type FROM accounts ORDER BY code",null);while(c.moveToNext())content.addView(text(c.getString(0)+"  |  "+c.getString(1)+"  |  "+c.getString(2),15));c.close();content.addView(action("📜 القيود اليومية",v->journal()));}
    void journal(){header("📜 القيود اليومية");Cursor c=db.getReadableDatabase().rawQuery("SELECT j.id,j.description,COALESCE(SUM(l.debit),0),COALESCE(SUM(l.credit),0),j.created_at FROM journal j LEFT JOIN journal_lines l ON l.journal_id=j.id GROUP BY j.id ORDER BY j.id DESC",null);while(c.moveToNext())content.addView(text("قيد #"+c.getLong(0)+" — "+c.getString(1)+"\nمدين: "+money(c.getDouble(2))+" = دائن: "+money(c.getDouble(3))+"\n"+c.getString(4),15));c.close();}

    void reports(){header("📈 التقارير المالية");content.addView(text("الملخص المالي",21));content.addView(text("المخزون: "+money(db.inventoryValue())+"\nالصندوق: "+money(db.cashBalance())+"\nالمبيعات: "+money(db.salesTotal())+"\nتكلفة المبيعات: "+money(db.cogs())+"\nالمشتريات: "+money(db.purchasesTotal())+"\nالرواتب: "+money(db.payroll())+"\nالنتيجة التقديرية: "+money(db.netResult()),17));content.addView(action("🖨️ طباعة الملخص",v->printFinancialReport()));}
    void cash(){header("💵 الصندوق");content.addView(text("الرصيد الحالي: "+money(db.cashBalance()),20));content.addView(action("＋ سند قبض",v->cashDialog("IN")));content.addView(action("− سند صرف",v->cashDialog("OUT")));Cursor c=db.getReadableDatabase().rawQuery("SELECT type,amount,description,created_at FROM cash_transactions ORDER BY id DESC",null);while(c.moveToNext())content.addView(text((c.getString(0).equals("IN")?"قبض ":"صرف ")+money(c.getDouble(1))+"\n"+c.getString(2)+" — "+c.getString(3),15));c.close();}
    void cashDialog(String type){EditText a=field("المبلغ",true),d=field("البيان",false);new AlertDialog.Builder(this).setTitle(type.equals("IN")?"سند قبض":"سند صرف").setView(box(a,d)).setPositiveButton("حفظ",(x,w)->{try{db.addCash(type,num(a),d.getText().toString());cash();}catch(Exception e){toast("تحقق من البيانات");}}).setNegativeButton("إلغاء",null).show();}

    void settings(){header("⚙ الإعدادات");content.addView(text("الترخيص: "+(license.isActivated()?"مفعل":"تجريبي — "+license.remainingDays()+" يوم"),17));content.addView(action("🔑 تغيير كلمة المرور",v->changePassword()));content.addView(action("⭐ تفعيل الترخيص",v->showActivation()));content.addView(action("✉️ مراسلة الدعم بالبريد",v->emailDialog()));content.addView(text("النسخة 1.0.1\nالتحديثات المستقبلية مصممة لتصل دون تغيير بيانات الشركة.",14));}
    void changePassword(){EditText old=field("كلمة المرور الحالية",false),n=field("كلمة المرور الجديدة",false),c=field("تأكيد الجديدة",false);old.setInputType(129);n.setInputType(129);c.setInputType(129);new AlertDialog.Builder(this).setTitle("تغيير كلمة المرور").setView(box(old,n,c)).setPositiveButton("حفظ",(d,w)->{if(!hash(old.getText().toString()).equals(prefs.getString("password_hash",""))){toast("كلمة المرور الحالية غير صحيحة");return;}if(n.length()<4||!n.getText().toString().equals(c.getText().toString())){toast("كلمة المرور الجديدة غير متطابقة");return;}prefs.edit().putString("password_hash",hash(n.getText().toString())).apply();toast("✓ تم تغيير كلمة المرور");}).setNegativeButton("إلغاء",null).show();}

    void emailDialog(){EditText to=field("البريد الإلكتروني",false),sub=field("الموضوع",false),body=field("الرسالة",false);body.setMinLines(5);new AlertDialog.Builder(this).setTitle("✉️ البريد الإلكتروني").setView(box(to,sub,body)).setPositiveButton("إرسال",(d,w)->{try{Intent i=new Intent(Intent.ACTION_SENDTO);i.setData(Uri.parse("mailto:"+Uri.encode(to.getText().toString().trim())));i.putExtra(Intent.EXTRA_SUBJECT,sub.getText().toString());i.putExtra(Intent.EXTRA_TEXT,body.getText().toString());startActivity(Intent.createChooser(i,"اختر تطبيق البريد الإلكتروني"));}catch(Exception e){toast("لا يوجد تطبيق بريد إلكتروني مثبت");}}).setNegativeButton("إلغاء",null).show();}

    String esc(String x){return x==null?"":x.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"", "&quot;");}
    void printHtml(String title,String html){WebView w=new WebView(this);w.setWebViewClient(new WebViewClient(){public void onPageFinished(WebView v,String u){PrintManager pm=(PrintManager)getSystemService(PRINT_SERVICE);pm.print(title,v.createPrintDocumentAdapter(title),new android.print.PrintAttributes.Builder().setMediaSize(android.print.PrintAttributes.MediaSize.ISO_A4).build());}});w.loadDataWithBaseURL(null,html,"text/html","UTF-8",null);}
    String accountant(){return prefs.getString("accountant_name","غير محدد");}
    void printInvoice(String type,long id){String table=type.equals("SALE")?"sales":"purchases";Cursor c=db.getReadableDatabase().rawQuery("SELECT id,total,paid,created_at FROM "+table+" WHERE id=?",new String[]{""+id});if(!c.moveToFirst()){c.close();return;}String html="<html dir='rtl'><meta charset='utf-8'><body style='font-family:sans-serif;padding:30px'><h1 style='text-align:center;color:#0B1F3A'>شركة محمد مصطفى الذكية</h1><h2>"+(type.equals("SALE")?"فاتورة بيع":"فاتورة شراء")+" #"+id+"</h2><hr><p>التاريخ: "+esc(c.getString(3))+"</p><p>الإجمالي: "+money(c.getDouble(1))+"</p><p>المدفوع: "+money(c.getDouble(2))+"</p><p>المتبقي: "+money(c.getDouble(1)-c.getDouble(2))+"</p><div style='margin-top:80px;border-top:1px solid #333;width:45%;padding-top:10px'>توقيع المحاسب<br>"+esc(accountant())+"</div></body></html>";c.close();printHtml("فاتورة #"+id,html);}
    void printFinancialReport(){String html="<html dir='rtl'><meta charset='utf-8'><body style='font-family:sans-serif;padding:30px'><h1 style='text-align:center;color:#0B1F3A'>شركة محمد مصطفى الذكية</h1><h2>الملخص المالي</h2><p>المخزون: "+money(db.inventoryValue())+"</p><p>الصندوق: "+money(db.cashBalance())+"</p><p>المبيعات: "+money(db.salesTotal())+"</p><p>تكلفة المبيعات: "+money(db.cogs())+"</p><p>المشتريات: "+money(db.purchasesTotal())+"</p><p>الرواتب: "+money(db.payroll())+"</p><h3>النتيجة التقديرية: "+money(db.netResult())+"</h3><div style='margin-top:80px;border-top:1px solid #333;width:45%;padding-top:10px'>توقيع المحاسب<br>"+esc(accountant())+"</div></body></html>";printHtml("الملخص المالي",html);}
}