using System;using System.IO;using System.Windows;using System.Windows.Controls;using Microsoft.Data.Sqlite;
namespace SmartCompany.Windows {
public partial class MainWindow:Window{
 readonly string dbPath=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"SmartCompany","smartcompany.db");
 public MainWindow(){InitializeComponent();Directory.CreateDirectory(Path.GetDirectoryName(dbPath)!);InitDb();Home();}
 SqliteConnection Open(){var c=new SqliteConnection("Data Source="+dbPath);c.Open();return c;}
 void InitDb(){using var c=Open();using var x=c.CreateCommand();x.CommandText=@"CREATE TABLE IF NOT EXISTS company(id INTEGER PRIMARY KEY,name TEXT,currency TEXT);CREATE TABLE IF NOT EXISTS accounts(id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT,name TEXT,type TEXT);CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,qty REAL,cost REAL,price REAL);CREATE TABLE IF NOT EXISTS customers(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,phone TEXT,balance REAL DEFAULT 0);CREATE TABLE IF NOT EXISTS suppliers(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,phone TEXT,balance REAL DEFAULT 0);CREATE TABLE IF NOT EXISTS employees(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,job TEXT,salary REAL DEFAULT 0,advance REAL DEFAULT 0);CREATE TABLE IF NOT EXISTS journal(id INTEGER PRIMARY KEY AUTOINCREMENT,description TEXT,debit REAL,credit REAL,created_at TEXT);";x.ExecuteNonQuery();}
 void Base(string title){PageTitle.Text=title;Page.Children.Clear();Page.Children.Add(new TextBlock{Text=title,FontSize=22,FontWeight=FontWeights.Bold,Foreground=FindResource("Navy") as System.Windows.Media.Brush,Margin=new Thickness(4,0,4,18)});}
 Button B(string s,RoutedEventHandler h){var b=new Button{Content=s};b.Click+=h;return b;}
 void Home(){Base("لوحة القيادة");using var c=Open();var rows=new StackPanel();foreach(var x in new[]{("المخزون","SELECT COALESCE(SUM(qty*cost),0) FROM products"),("العملاء","SELECT COALESCE(SUM(balance),0) FROM customers"),("الموردون","SELECT COALESCE(SUM(balance),0) FROM suppliers")}){using var q=c.CreateCommand();q.CommandText=x.Item2;var v=Convert.ToDouble(q.ExecuteScalar());rows.Children.Add(new TextBlock{Text=x.Item1+": "+v.ToString("N2")+" جنيه",FontSize=20,Margin=new Thickness(8)});}Page.Children.Add(rows);Page.Children.Add(new TextBlock{Text="نظام محاسبي احترافي قابل للتحديث والتوسع إلى الحسابات الكاملة والمخزون والرواتب والتقارير.",FontSize=16,Margin=new Thickness(8,25,8,8)});}
 void Simple(string title,string msg){Base(title);Page.Children.Add(new TextBlock{Text=msg,FontSize=18,Margin=new Thickness(8)});}
 void Home_Click(object s,RoutedEventArgs e){Home();}void Sales_Click(object s,RoutedEventArgs e){Simple("🧾 المبيعات والفواتير","إدارة الفواتير، التحصيل، العملاء، والقيود المرتبطة بالمبيعات.");}void Purchases_Click(object s,RoutedEventArgs e){Simple("🛒 المشتريات","إدارة الموردين وفواتير الشراء وتحديث المخزون.");}void Inventory_Click(object s,RoutedEventArgs e){Simple("📦 المخزون والمخازن","الأصناف، الكميات، التكلفة، التحويلات والجرد.");}void Customers_Click(object s,RoutedEventArgs e){Simple("👥 العملاء","بيانات العملاء والأرصدة والتحصيلات.");}void Suppliers_Click(object s,RoutedEventArgs e){Simple("🚚 الموردون","بيانات الموردين والأرصدة والمدفوعات.");}void Employees_Click(object s,RoutedEventArgs e){Simple("👔 الموظفون والرواتب","الموظفون، الوظائف، الرواتب، السلف والخصومات.");}void Accounts_Click(object s,RoutedEventArgs e){Simple("📒 الحسابات والقيود","دليل الحسابات، القيود اليومية، دفتر الأستاذ وميزان المراجعة.");}void Reports_Click(object s,RoutedEventArgs e){Simple("📈 التقارير المالية","قائمة الدخل، الميزانية العمومية، التدفقات النقدية، والمخزون.");}void Settings_Click(object s,RoutedEventArgs e){Simple("⚙ الإعدادات","الترخيص، النسخ الاحتياطي، المستخدمون والصلاحيات، والتحديثات.");}
}}